### ISSUE TITLE
ValueError: 'full_model' is not a valid GradientClipType

### ISSUE THREAD

**Issue by uowei** [postech-ami/Uni-DVPS#1]
Hello, I am a beginner in this field. 

I encountered this issue while attempting to retrain the model. 

Could you please advise how I can resolve it? I haven’t found many cases online with this issue.

Could it be that my Detectron version is incorrect? 

However, I followed the steps in your README, and the only possible difference is that my CUDA version is 12.2.

```
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    args=(args,),
  File "/mnt/d/Uni-DVPS-main/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train.py", line 154, in main
    trainer = Trainer(cfg)
  File "/mnt/d/Uni-DVPS-main/detectron2/detectron2/engine/defaults.py", line 377, in __init__
    optimizer = self.build_optimizer(cfg, model)
  File "/mnt/d/Uni-DVPS-main/detectron2/detectron2/engine/defaults.py", line 528, in build_optimizer
    return build_optimizer(cfg, model)
  File "/mnt/d/Uni-DVPS-main/detectron2/detectron2/solver/build.py", line 125, in build_optimizer
    return maybe_add_gradient_clipping(cfg, torch.optim.SGD)(
  File "/mnt/d/Uni-DVPS-main/detectron2/detectron2/solver/build.py", line 103, in maybe_add_gradient_clipping
    grad_clipper = _create_gradient_clipper(cfg.SOLVER.CLIP_GRADIENTS)
  File "/mnt/d/Uni-DVPS-main/detectron2/detectron2/solver/build.py", line 41, in _create_gradient_clipper
    return _GRADIENT_CLIP_TYPE_TO_CLIPPER[GradientClipType(cfg.CLIP_TYPE)]
  File "/home/mediacore/anaconda3/envs/unidvps/lib/python3.7/enum.py", line 315, in __call__
    return cls.__new__(cls, value)
  File "/home/mediacore/anaconda3/envs/unidvps/lib/python3.7/enum.py", line 569, in __new__
    raise exc
  File "/home/mediacore/anaconda3/envs/unidvps/lib/python3.7/enum.py", line 553, in __new__
    result = cls._missing_(value)
  File "/home/mediacore/anaconda3/envs/unidvps/lib/python3.7/enum.py", line 582, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'full_model' is not a valid GradientClipType
```

Thanks!

**Comment by J1Yeon-Kim** [comment]
Please make sure that Detectron2 version is same as the one written in README (1315c8977e867b9979b4fa712638c1975ca8c78f).

I strongly recommend you to install same CUDA and torch version written in README.

**Comment by J1Yeon-Kim** [comment]
Please reopen this issue if you need more help regarding this.
